# Site settings
title: 当我成为背影时
description: "spacemacs 主题界面"
baseurl: "/theme-space" 
url: ""  
#but in production: 'https://ljq199612.github.io/theme-space'

# User settings
username: 灿烂人生
user_title: Believe it 
email: ljq1483858517@163.com
github_username: ljq199612
gitbook_url:  http://ljq199612.github.io/Volume/_book/index.html
linkedin_public_url: #
disqus_username: #
profile_picture:  https://ljq199612.github.io/theme-space/blog-author.jpg

#https://octodex.github.com/images/mummytocat.gif


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /theme-space
      key_trigger: 1
    - title: posts
      url: /theme-space/posts
      key_trigger: 2
    - title: series
      url: /theme-space/series
      key_trigger: 3
    - title: tags
      url: /theme-space/tags
      key_trigger: 4
    - title: about me
      url: /theme-space/about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/ljq199612
      new_tab: true
      key_trigger: g
    - title: gitbook
      url: http://ljq199612.github.io/Volume/_book/index.html
      new_tab: true
      key_trigger: b
    - title: search
      url: #
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/ljq199612/vim-frontend
  - name: generator-capybara
    url: https://github.com/ljq199612/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
