# Site settings
title: ljq的-小屋
description: "spacemacs 主题界面.."
baseurl: "/theme-space" 
url: ""  
#but in production: 'https://ljq199612.github.io/theme-space'

# User settings
username: I can
user_title: Believe it 
email: ljq1483858517@163.com
twitter_username: #
github_username:  ljq199612
gplus_username:   #
linkedin_public_url: loremipsum 
disqus_username: loremipsum
profile_picture: https://ljq199612.github.io/theme-space/blog-author.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /theme-space
      key_trigger: 1
    - title: posts
      url: /theme-space/posts
      key_trigger: 2
    - title: series
      url: /theme-space/series
      key_trigger: 3
    - title: tags
      url: /theme-space/tags
      key_trigger: 4
    - title: about me
      url: /theme-space/about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/ljq199612
      new_tab: true
      key_trigger: g
    - title: gitbook
      url: http://ljq199612.github.io/Volume/_book/index.html
      new_tab: true
      key_trigger: b
    - title: twitter
      url: #
      key_trigger: t
    - title: search
      url: #
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/ljq199612/vim-frontend
  - name: generator-capybara
    url: https://github.com/ljq199612/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
